import '../../common/extends-7477639a.js';
import '../../common/objectWithoutPropertiesLoose-d5128f55.js';
import '../../common/defaultTheme-74fc985b.js';
import '../../common/_commonjsHelpers-8c19dec8.js';
import '../../common/index-57a74e37.js';
import '../../common/index-ce016b4a.js';
import '../../common/clsx.m-e1755476.js';
import '../../common/getThemeProps-6712df0a.js';
import '../../common/inheritsLoose-b67f434e.js';
import '../../common/assertThisInitialized-8eae6022.js';
import '../../common/useTheme-6c30e9f6.js';
import '../../common/hoist-non-react-statics.cjs-ec82709f.js';
import '../../common/withStyles-aba2468b.js';
import '../../common/capitalize-500844e3.js';
import { _ as __pika_web_default_export_for_treeshaking__ } from '../../common/Typography-bbc189f5.js';
export { _ as default } from '../../common/Typography-bbc189f5.js';
